EINw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from EINw import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),

    # Users
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('portfolio/', views.userportfolio, name='userportfolio'),
    path('favorite/', views.userfavorite, name='userfavorite'),

    # Projects
    path('equities/', include('equities.urls')),
    path('icos/', include('icos.urls')),
    path('ipos/', include('ipos.urls')),
    path('loans/', include('loans.urls')),
    path('advertising/', include('advertising.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equities/urls.py
from django.urls import path
from . import views

app_name = 'equities'

urlpatterns = [
    path('', views.index, name='equities_index'),
    path('filters/', views.filters, name='equities_filters'),
    path('<slug:equities_slug>/', views.detail, name='detail'),
]

equities/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.utils.text import slugify
from common.models import Currency, SectorChoice


class EquityProject(models.Model):
    image = models.ImageField(upload_to='equities/db/images/',)
    title = models.CharField(max_length=25,)
    url = models.URLField(blank=False, )
    country = models.ForeignKey(
        'common.Country',
        to_field="country_code",
        on_delete=models.DO_NOTHING,
        null=True,
    )
    end_date = models.DateField(
        blank=False,
        help_text="Day to go + date now",
    )
    currency = models.ForeignKey(
        'common.Currency',
        to_field="currency_abbr",
        on_delete=models.DO_NOTHING,
        null=True,
    )
    invested = models.PositiveSmallIntegerField(blank=False,)
    round_money = models.PositiveSmallIntegerField(
        blank=False,
        help_text="Target or Max round",
    )

    pre_money_valuation = models.PositiveSmallIntegerField(blank=False,)
    min_investment_amount = models.PositiveSmallIntegerField(blank=False,)

    sector_choice = models.ForeignKey(
        'common.SectorChoice',
        to_field="sector_name",
        on_delete=models.DO_NOTHING,
        null=True,
        default='NONE',
        help_text="In classification of yahoo.finance",
    )

    date_last_modified = models.DateTimeField(
        auto_now=True,
        editable=False,
    )
    add_date_time = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    slug = models.SlugField(
        default='',
        null=False,
        db_index=True,
        editable=False,
    )
    is_active = models.CharField(
        default='',
        null=False,
        db_index=True,
        editable=False,
        max_length=6,
    )
    score = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        editable=True,
        default=0,
        db_index=True,
    )

    @property
    def status(self, *args, **kwargs):
        if date.today() > self.end_date:
            res = "ENDED"
        else:
            res = "ACTIVE"
        self.is_active = res
        self.slug = slugify(self.title)
        super(EquityProject, self).save(*args, **kwargs)
        return res

    @property
    def min_amount(self):
        if self.currency_id in ['GBP', 'EUR']:
            return f'{self.min_investment_amount:,} {self.currency.currency_sign}'
        else:
            return f'{self.currency.currency_sign} {self.min_investment_amount:,}'

    @property
    def pre_money_val(self):
        if self.currency_id in ['GBP', 'EUR']:
            return f'{self.pre_money_valuation:,} {self.currency.currency_sign}'
        else:
            return f'{self.currency.currency_sign} {self.pre_money_valuation:,}'

    @property
    def round_raised(self):
        if self.currency_id in ['GBP', 'EUR']:
            return f'{self.invested:,} {self.currency.currency_sign} of ' \
               f'{self.round_money:,} {self.currency.currency_sign}'
        else:
            return f'{self.currency.currency_sign} {self.invested:,} of ' \
                   f'{self.currency.currency_sign} {self.round_money:,}'

    @property
    def raised_percent(self):
        return ((self.invested *10000) // self.round_money) / 100

    @property
    def days_to_go(self):
        return self.end_date - date.today()

    @property
    def country_flag(self):
        return self.country.country_flag.url

    @property
    def country_code(self):
        return self.country_id

    def get_url(self):
        return reverse('detail', args=[self.slug])

    def __str__(self):
        return self.title

equities/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .models import EquityProject
from common.views import pagination, currencies_list, sectors_list
from datetime import date, timedelta


def index(request):
    paginate_by = request.GET.get('paginate_by') or 5
    page = request.GET.get('page')
    equity_projects = EquityProject.objects.filter(~Q(is_active='ENDED')).order_by('-add_date_time')
    for project in equity_projects:
        project.save()
    page_obj = pagination(equity_projects, page, paginate_by)

    return render(request, 'equities/index.html', {
        'page_obj': page_obj,
        'currencies': currencies_list(),
        'sectors': sectors_list(),
        'paginate_by': paginate_by,
    })


def filters(request):
    page = request.GET.get('page')

    paginate_by = request.GET.get('paginate_by') or 5

    currency_get = request.GET.getlist('currency')
    if not currency_get:
        currency_get = currencies_list()

    sector_get = request.GET.getlist('sector')
    if not sector_get:
        sector_get = sectors_list()

    score_get = request.GET.get('score').split(sep=";")
    score_get_min = score_get[0]
    score_get_max = score_get[1]

    days_to_go_get = request.GET.get('days_to_go').split(sep=";")
    date_to_go_get_from = date.today() + timedelta(days=int(days_to_go_get[0]))
    date_to_go_get_to = date.today() + timedelta(days=int(days_to_go_get[1]))

    min_invest_get = request.GET.get('min_invest').split(sep=";")
    min_invest_get_min = min_invest_get[0]
    min_invest_get_max = min_invest_get[1]

    raised_get = request.GET.get('raised').split(sep=";")
    raised_get_min = raised_get[0]
    raised_get_max = raised_get[1]

    equity_projects_queryset = EquityProject.objects.filter(
        ~Q(is_active='ENDED'),
        Q(currency_id__in=currency_get),
        Q(sector_choice_id__in=sector_get),
        Q(score__gte=score_get_min) & Q(score__lte=score_get_max),
        Q(end_date__gte=date_to_go_get_from) & Q(end_date__lte=date_to_go_get_to),
        Q(min_investment_amount__gte=min_invest_get_min) & Q(min_investment_amount__lte=min_invest_get_max)
    ).order_by('-add_date_time')

    equity_projects_queryset_filtered = []
    for eq in equity_projects_queryset:
        per = eq.invested * 100 / eq.round_money
        if (per >= float(raised_get_min)) and (per <= float(raised_get_max)):
            equity_projects_queryset_filtered.append(eq)

    page_obj = pagination(equity_projects_queryset_filtered, page, paginate_by)

    return render(request, 'equities/filters.html', {
        'page_obj': page_obj,
        'currencies': currencies_list(),
        'sectors': sectors_list(),
        'paginate_by': paginate_by,
    })


def detail(request, equities_slug: str):
    equities = get_object_or_404(EquityProject, slug=equities_slug)
    return render(request, 'equities/detail.html', {'equities': equities})

equities/templates/equities/eqcommon/eqtable.html
{% block eqtable %}
    <thead>
        <tr>
            <th colspan="3">Project title</th>
            <th style="text-align:end">Min invest</th>
            <th style="text-align:end">Pre-money</th>
            <th style="text-align:end">Round</th>
            <th style="text-align:end">1d / 7d change</th>
            <th style="text-align:end">Days to go</th>
            <th style="text-align:end">Score</th>
        </tr>
    </thead>
    <tbody>
        {% for project in page_obj %}
            <tr>
                {% if project.status == 'ACTIVE' %}
                    <td>
                        <i class="bi bi-star text-color-yellow"></i>
                    </td>
                    <td>
                        <div class="table-pic-block">
                                <img src="{{  project.image.url }}" alt="">
                        </div>
                    </td>
                    <td>
                        <a href="{% url 'equities:detail' project.slug %}" class="grey-link">
                            <div class="text-norm"> {{ project.title }} </div>
                        </a>
                        <div class="martop--1">
                            <span class="app-pill-sector">{{ project.sector_choice }}</span>
                            <span class="app-pill-country align-items-center">
                                <img src="{{ project.country_flag }}" alt="" >
                                {{ project.country_code }}
                            </span>
                        </div>
                    </td>
                    <td style="text-align:end">{{ project.min_amount }}</td>
                    <td style="text-align:end">{{ project.pre_money_val }}</td>
                    <td style="text-align:end">
                        <div>
                            {% if project.raised_percent > 100 %}
                                <span class="app-pill-overfunding">Overfunding</span>
                            {% endif %}
                            {{ project.raised_percent }} %
                        </div>
                        <div class="text-color-blue text-xsmall martop--1">
                            {{ project.round_raised }}
                        </div>
                    </td>
                    <td style="text-align:end">
                        <div>
                            <span class="text-color-green">+2.5%</span> / <span class="text-color-red">+8.0%</span>
                        </div>
                    </td>
                    <td>
                        <div class="d-flex justify-content-end">
                            <span class="align-self-center">
                                {{ project.days_to_go.days}}
                            </span>
                        </div>
                    </td>
                    <td>
                        <div class="d-flex justify-content-end">
                            <span class="align-self-center text-bold">
                            {{ project.score }}
                            </span>
                            <div class="p-1 align-self-end">
                                {% if project.score > 9 %}
                                    <i class="bi bi-star-fill text-color-yellow"></i>
                                {% elif project.score > 8 %}
                                    <i class="bi bi-reception-4 text-color-green"></i>
                                {% elif project.score > 7 %}
                                    <i class="bi bi-reception-3 text-color-yellow"></i>
                                {% elif project.score > 6 %}
                                    <i class="bi bi-reception-2 text-color-red"></i>
                                {% elif project.score > 5 %}
                                    <i class="bi bi-reception-2 text-color-red"></i>
                                {% else %}
                                    <i class="bi bi-reception-0 text-color-blue"></i>
                                {% endif %}
                            </div>
                        </div>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </tbody>
{% endblock eqtable %}