EINw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from EINw import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),

    # Users
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('portfolio/', views.userportfolio, name='userportfolio'),
    path('favorite/', views.userfavorite, name='userfavorite'),

    # Projects
    path('equities/', include('equities.urls')),
    path('icos/', include('icos.urls')),
    path('ipos/', include('ipos.urls')),
    path('loans/', include('loans.urls')),
    path('advertising/', include('advertising.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equities/urls.py
from django.urls import path
from . import views

app_name = 'equities'

urlpatterns = [
    path('', views.index, name='equities_index'),
    path('filters/', views.filters, name='equities_filters'),
    path('<slug:equities_slug>/', views.detail, name='detail'),
]

equities/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.utils.text import slugify
from common.models import Currency, SectorChoice


class EquityProject(models.Model):
    image = models.ImageField(upload_to='equities/db/images/',)
    title = models.CharField(max_length=25,)
    url = models.URLField(blank=False, )
    country = models.ForeignKey(
        'common.Country',
        to_field="country_code",
        on_delete=models.DO_NOTHING,
        null=True,
    )
    end_date = models.DateField(
        blank=False,
        help_text="Day to go + date now",
    )
    currency = models.ForeignKey(
        'common.Currency',
        to_field="currency_abbr",
        on_delete=models.DO_NOTHING,
        null=True,
    )
    invested = models.PositiveSmallIntegerField(blank=False,)
    round_money = models.PositiveSmallIntegerField(
        blank=False,
        help_text="Target or Max round",
    )

    pre_money_valuation = models.PositiveSmallIntegerField(blank=False,)
    min_investment_amount = models.PositiveSmallIntegerField(blank=False,)

    sector_choice = models.ForeignKey(
        'common.SectorChoice',
        to_field="sector_name",
        on_delete=models.DO_NOTHING,
        null=True,
        default='NONE',
        help_text="In classification of yahoo.finance",
    )

    date_last_modified = models.DateTimeField(
        auto_now=True,
        editable=False,
    )
    add_date_time = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )
    slug = models.SlugField(
        default='',
        null=False,
        db_index=True,
        editable=False,
    )
    is_active = models.CharField(
        default='',
        null=False,
        db_index=True,
        editable=False,
        max_length=6,
    )
    score = models.DecimalField(
        max_digits=3,
        decimal_places=1,
        editable=True,
        default=0,
        db_index=True,
    )

    @property
    def status(self, *args, **kwargs):
        if date.today() > self.end_date:
            res = "ENDED"
        else:
            res = "ACTIVE"
        self.is_active = res
        self.slug = slugify(self.title)
        super(EquityProject, self).save(*args, **kwargs)
        return res

    @property
    def min_amount(self):
        if self.currency_id in ['GBP', 'EUR']:
            return f'{self.min_investment_amount:,} {self.currency.currency_sign}'
        else:
            return f'{self.currency.currency_sign} {self.min_investment_amount:,}'

    @property
    def pre_money_val(self):
        if self.currency_id in ['GBP', 'EUR']:
            return f'{self.pre_money_valuation:,} {self.currency.currency_sign}'
        else:
            return f'{self.currency.currency_sign} {self.pre_money_valuation:,}'

    @property
    def round_raised(self):
        if self.currency_id in ['GBP', 'EUR']:
            return f'{self.invested:,} {self.currency.currency_sign} of ' \
               f'{self.round_money:,} {self.currency.currency_sign}'
        else:
            return f'{self.currency.currency_sign} {self.invested:,} of ' \
                   f'{self.currency.currency_sign} {self.round_money:,}'

    @property
    def raised_percent(self):
        return ((self.invested *10000) // self.round_money) / 100

    @property
    def days_to_go(self):
        return self.end_date - date.today()

    @property
    def country_flag(self):
        return self.country.country_flag.url

    @property
    def country_code(self):
        return self.country_id

    def get_url(self):
        return reverse('detail', args=[self.slug])

    def __str__(self):
        return self.title

equities/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .models import EquityProject
from common.views import pagination, currencies_list, sectors_list
from datetime import date, timedelta


def index(request):
    paginate_by = request.GET.get('paginate_by') or 5
    page = request.GET.get('page')
    equity_projects = EquityProject.objects.filter(~Q(is_active='ENDED')).order_by('-add_date_time')
    for project in equity_projects:
        project.save()
    page_obj = pagination(equity_projects, page, paginate_by)

    return render(request, 'equities/index.html', {
        'page_obj': page_obj,
        'currencies': currencies_list(),
        'sectors': sectors_list(),
        'paginate_by': paginate_by,
    })


def filters(request):
    page = request.GET.get('page')

    paginate_by = request.GET.get('paginate_by') or 5

    currency_get = request.GET.getlist('currency')
    if not currency_get:
        currency_get = currencies_list()

    sector_get = request.GET.getlist('sector')
    if not sector_get:
        sector_get = sectors_list()

    score_get = request.GET.get('score').split(sep=";")
    score_get_min = score_get[0]
    score_get_max = score_get[1]

    days_to_go_get = request.GET.get('days_to_go').split(sep=";")
    date_to_go_get_from = date.today() + timedelta(days=int(days_to_go_get[0]))
    date_to_go_get_to = date.today() + timedelta(days=int(days_to_go_get[1]))

    min_invest_get = request.GET.get('min_invest').split(sep=";")
    min_invest_get_min = min_invest_get[0]
    min_invest_get_max = min_invest_get[1]

    raised_get = request.GET.get('raised').split(sep=";")
    raised_get_min = raised_get[0]
    raised_get_max = raised_get[1]

    equity_projects_queryset = EquityProject.objects.filter(
        ~Q(is_active='ENDED'),
        Q(currency_id__in=currency_get),
        Q(sector_choice_id__in=sector_get),
        Q(score__gte=score_get_min) & Q(score__lte=score_get_max),
        Q(end_date__gte=date_to_go_get_from) & Q(end_date__lte=date_to_go_get_to),
        Q(min_investment_amount__gte=min_invest_get_min) & Q(min_investment_amount__lte=min_invest_get_max)
    ).order_by('-add_date_time')

    equity_projects_queryset_filtered = []
    for eq in equity_projects_queryset:
        per = eq.invested * 100 / eq.round_money
        if (per >= float(raised_get_min)) and (per <= float(raised_get_max)):
            equity_projects_queryset_filtered.append(eq)

    page_obj = pagination(equity_projects_queryset_filtered, page, paginate_by)

    return render(request, 'equities/filters.html', {
        'page_obj': page_obj,
        'currencies': currencies_list(),
        'sectors': sectors_list(),
        'paginate_by': paginate_by,
    })


def detail(request, equities_slug: str):
    equities = get_object_or_404(EquityProject, slug=equities_slug)
    return render(request, 'equities/detail.html', {'equities': equities})

equities/templates/equities/detail.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
	{{ equities.title }}
{% endblock %}


{% block content %}
	<h1>{{ equities.title }}</h1>
	<img src="{{ equities.image.url }}" height="60" alt="{{ equities.title }}">
	<h2>
		<a href="{{ equities.url }}">
			{{ equities.title }}
		</a>
	</h2>
	<p>
		{{ equities.type_of_investment }}
		{{ equities.days_to_go }}
		{{ equities.invested }}
		{{ equities.min_round }}
		{{ equities.max_round }}
		{{ equities.pre_money_valuation }}
		{{ equities.min_investment_amount }}
		{{ equities.sector }}
		{{ equities.industry }}
		{{ equities.date }}
	</p>
{% endblock %}

equities/templates/equities/filters.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	Equities
{% endblock %}

{% block content %}
    <div class="container">

        <!-- Tablenavbar -->
        <div class="row">
            {% block tablenavbar %}
                {% include 'tablenav/tablenavbar.html' %}
            {% endblock tablenavbar %}
        </div>

         <!-- Filter's block for filters from tablenavbar -->
        <div class="row">
            {% block filtersform %}
                {% include 'equities/filtersform.html' %}
            {% endblock filtersform %}
        </div>

        <!-- Table -->
        <div class="row">
            <div class="table-responsive">
                <table class="table table-hover" id="Equities_Table_Filtered">
                    {% block eqtable %}
                        {% include 'equities/eqcommon/eqtable.html' %}
                    {% endblock eqtable %}
                </table>
            </div>
        </div>

        <!-- Table footer -->
        {% block tablefooter %}
            {% include 'tablenav/tablefooter.html' %}
        {% endblock tablefooter %}
	</div>
{% endblock content %}

equities/templates/equities/filtersform.html
{% load static %}

{% block filtersform %}
    <div class="collapse py-2" id="equitiesFilter">
        <div class="filter-card">
            <div class="container">
                <form action="{% url 'equities:equities_filters' %}" method="get" name="equity_filter">
                    <div class="row">
                        <div class="col-6">
                            <span class="text-color-blue">Raised, %:</span>
                            <input class="text-small" type="text" name="raised" id="raised">
                            <label for="raised"></label>
                        </div>
                        <div class="col-6">
                            <span class="text-color-blue">Score:</span>
                            <input class="text-small" type="text" name="score" id="score">
                            <label for="score"></label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6">
                            <span class="text-color-blue">Days to go:</span>
                            <input class="text-small" type="text" name="days_to_go" id="days_to_go">
                            <label for="days_to_go"></label>
                        </div>
                        <div class="col-6">
                            <span class="text-color-blue">Min invest:</span>
                            <input class="text-small" type="text" name="min_invest" id="min_invest">
                            <label for="min_invest"></label>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <span class="text-color-blue pb-2">Sector: </span><br>
                        <div class="col-12">
                            {% for sector in sectors %}
                                <div class="form-check form-check-inline ms-2">
                                    <input class="form-check-input" type="checkbox" name="sector" id="sector{{ sector }}" value="{{ sector }}">
                                    <label class="form-check-label" for="sector{{ sector }}">{{ sector }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="row">
                        <span class="text-color-blue pb-2">Currencies: </span>
                        <div class="col-12">
                            {% for currency in currencies %}
                                <div class="form-group form-check-inline ms-2">
                                    <input class="form-check-input" type="checkbox" name="currency" id="currency{{ currency }}" value="{{ currency }}">
                                    <label class="form-check-label" for="currency{{ currency }}">{{ currency }}</label>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <a href="{% url 'equities:equities_index' %}">
                            <button type="button" class="btn btn-login pe-3 ps-3 me-3" style="text-decoration: none">
                                Reset filters
                            </button>
                        </a>
                        <button type="submit" class="btn btn-primary">Show results</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock filtersform %}

equities/templates/equities/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
	Equities
{% endblock %}

{% block content %}
    <div class="container">
        <!-- Table name -->
        <div class="table-name">
            Actual pre-IPO opportunities
        </div>

        <!-- Tablenavbar -->
        <div class="row">
            {% block tablenavbar %}
                {% include 'tablenav/tablenavbar.html' %}
            {% endblock tablenavbar %}
        </div>

         <!-- Filter's block for filters from tablenavbar -->
        <div class="row">
            {% block filtersform %}
                {% include 'equities/filtersform.html' %}
            {% endblock filtersform %}
        </div>


        <!-- Table -->
        <div class="row">
            <div class="table-responsive">
                <table class="table table-hover" id="Equities_Table">
                    {% block eqtable %}
                        {% include 'equities/eqcommon/eqtable.html' %}
                    {% endblock eqtable %}
                </table>
            </div>
        </div>

        <!-- Table footer -->
        {% block tablefooter %}
            {% include 'tablenav/tablefooter.html' %}
        {% endblock tablefooter %}
	</div>
{% endblock content %}