EINw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from EINw import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),

    # Users
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),
    path('portfolio/', views.userportfolio, name='userportfolio'),
    path('favorite/', views.userfavorite, name='userfavorite'),

    # Projects
    path('equities/', include('equities.urls')),
    path('icos/', include('icos.urls')),
    path('ipos/', include('ipos.urls')),
    path('loans/', include('loans.urls')),
    path('advertising/', include('advertising.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equities/urls.py
from django.urls import path
from . import views

app_name = 'equities'

urlpatterns = [
    path('', views.index, name='equities_index'),
    path('filters/', views.filters, name='equities_filters'),
    path('<slug:equities_slug>/', views.detail, name='detail'),
]

icos/urls.py
from django.urls import path
from . import views

app_name = 'icos'

urlpatterns = [
    path('', views.index, name='icos_index'),
    path('<int:icos_id>/', views.detail, name='detail'),
]

ipos/urls.py
from django.urls import path
from . import views

app_name = 'ipos'

urlpatterns = [
    path('', views.index, name='ipos_index'),
    path('<int:ipos_id>/', views.detail, name='detail'),
]

loans/urls.py
from django.urls import path
from . import views

app_name = 'loans'

urlpatterns = [
    path('', views.index, name='loans_index'),
    path('<int:loans_id>/', views.detail, name='detail'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

	<!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Investment opportunities' aggregator" name="description" />
    <meta content="the10.team" name="the10.team" />

	<!-- Page title -->
	<title>{% block title %}{% endblock title %} | EquityInNet - online investment opportunities' aggregator</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500&display=swap" rel="stylesheet">

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}">

	<!-- Bootstrap CSS -->
	<link href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
	<link href="{% static 'libs/bootstrap-icons/bootstrap-icons.css' %}" id="bootstrap-icons-style" rel="stylesheet" type="text/css" />
	<!-- App CSS -->
	<link href="{% static 'css/app.css' %}" id="app-style" rel="stylesheet" type="text/css" />
	<!-- OwlCarousel CSS -->
	<link href="{% static 'libs/owlcarousel/owl.carousel.min.css' %}" id="owl-style" rel="stylesheet" type="text/css" />
	<link href="{% static 'libs/owlcarousel/owl.theme.default.min.css' %}" id="owl-theme-style" rel="stylesheet" type="text/css" />
	<!-- Animate CSS -->
	<link href="{% static 'libs/animate.css/animate.min.css' %}" id="owl-style" rel="stylesheet" type="text/css" />
    <!-- Ion Range Slider CSS -->
    <link href="{% static 'libs/ion-rangeslider/css/ion.rangeSlider.min.css' %}" rel="stylesheet" type="text/css" />

    {% block extracss %}{% endblock extracss %}

</head>

<body>
	{% block topstatwidget %}
		{% include 'topstatwidget.html' %}
	{% endblock topstatwidget %}

	{% block header %}
		{% include 'header.html' %}
	{% endblock header %}

	<div class="block-divider"></div>

	{% block carousel %}
		{% include 'carousel.html' %}
	{% endblock carousel %}

	<div class="block-divider"></div>

	{% block content %}
	{% endblock content %}

    {% block footer %}
        {% include 'footer.html' %}
    {% endblock footer %}

	<!-- JavaScript -->
	<script src="{% static 'libs/jquery/jquery-3.6.0.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'libs/owlcarousel/owl.carousel.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'libs/bootstrap/js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'libs/ion-rangeslider/js/ion.rangeSlider.min.js' %}"></script>
	<script src="{% static 'js/app.js' %}"></script>
    {% block extrajs %}{% endblock extrajs %}
</body>

templates/carousel.html
{% load static %}
{% block carousel %}
    <div class="container">
        <div class="row">
            <div id="carousel-1" class="owl-carousel">
                {% for ads in carousel_ads %}
                    <div class="carousel-block">
                        <a target="_blank" href="{{ ads.url }}" class="nav-link">
                            <div class="carousel-pic-block">
                                <img src="{{ ads.image.url }}" alt="">
                            </div>
                            <span class="chapter">{{ ads.chapter}}</span><br>
                            <span class="title">{{ ads.title}}</span>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
	</div>
{% endblock carousel %}

templates/footer.html
{% load static %}
{% block footer %}

    <footer class="border-top pt-5 mt-5">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <a href="{% url 'index' %}" role="img" aria-label="EquityInNetLogo-full" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
                        <img src="{% static 'images/bluelogo-beta.svg' %}" alt="" height="30">
                    </a>
                </div>

                <div class="col-2">
                  <h5>Opportunities</h5>
                  <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="{% url 'equities:equities_index' %}" class="nav-link p-0 text-muted">Equity</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'ipos:ipos_index' %}" class="nav-link p-0 text-muted">IPO</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'icos:icos_index' %}" class="nav-link p-0 text-muted">ICO</a></li>
                    <li class="nav-item mb-2"><a href="{% url 'loans:loans_index' %}" class="nav-link p-0 text-muted">Loan's</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Fund's</a></li>
                  </ul>
                </div>

                <div class="col-2">
                  <h5>Ratings</h5>
                  <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">IPO broker's</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">ICO platform's</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Raising platform's</a></li>
                  </ul>
                </div>

                <div class="col-2">
                  <h5>Other</h5>
                  <ul class="nav flex-column">
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">What we do</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                  </ul>
                </div>

            </div>
            <div class="row">
                <div class="d-flex justify-content-between pt-4 mt-4 border-top">
                    <p class="text-muted">&copy; 2021-2022 EquityInNet, Inc. All rights reserved.</p>
                    <ul class="list-unstyled d-flex">
                        <li class="ms-3 bi bi-telegram"><a class="link-dark" href="#"></a></li>
                        <li class="ms-3 bi bi-facebook"><a class="link-dark" href="#"></a></li>
                        <li class="ms-3 bi bi-envelope-fill"><a class="link-dark" href="#"></a></li>
                    </ul>
                </div>
                <div class="d-flex justify-content-end pb-4">
                    <span class="text-color-dark-grey">Powered by &zwnj;</span><span class="text-color-blue d-inline-block">the10.team</span>
                </div>
            </div>
        </div>
    </footer>

{% endblock footer %}

templates/header.html
{% load static %}
{% block header %}

	<div class="toptab">
		<div class="container">
            <div class="row">

                <!-- Main logo -->
                <div class="col-2" >
                    <div class="my-3">
                        <a href="{% url 'index' %}" role="img" aria-label="EquityInNetLogo-full">
                            <img src="{% static 'images/bluelogo-beta.svg' %}" alt="" height="30">
                        </a>
                    </div>
                </div>

                <!-- Navbar -->
                <div class="col-7 align-self-center">
                    <nav class="navbar navbar-expand-lg">
                        <div id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown pe-3">
                                    <a class="nav-link link-dark"
                                       id="navbarDropdownOpportunities" role="button" data-bs-toggle="dropdown"
                                       aria-haspopup="true" aria-expanded="false">
                                        Opportunities
                                        <i class="bi bi-chevron-down"></i>
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownOpportunities">
                                        <li>
                                            <a class="dropdown-item" href="{% url 'equities:equities_index' %}">
                                                <i class="bi bi-pie-chart text-color-yellow me-2"></i>
                                                Equity
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'ipos:ipos_index' %}">
                                                <i class="bi-bank text-color-yellow me-2"></i>
                                                IPO
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'icos:icos_index' %}">
                                                <i class="bi bi-currency-bitcoin text-color-yellow me-2"></i>
                                                ICO
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="{% url 'loans:loans_index' %}">
                                                <i class="bi bi-percent text-color-yellow me-2"></i>
                                                Loan's
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="#">
                                                <i class="bi bi-wallet text-color-yellow me-2"></i>
                                                Fund's
                                            </a>
                                        </li>
                                    </ul>
                                </li>

                                <li class="nav-item dropdown pe-3">
                                    <a class="nav-link link-dark"
                                       id="navbarDropdownRating" role="button" data-bs-toggle="dropdown"
                                       aria-haspopup="true" aria-expanded="false">
                                        Ratings
                                        <i class="bi bi-chevron-down"></i>
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownRating">
                                        <li>
                                            <a class="dropdown-item" href="#">
                                                <i class="bi bi-person text-color-yellow me-2"></i>
                                                IPO broker's
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="#">
                                                <i class="bi bi-coin text-color-yellow me-2"></i>
                                                ICO platform's
                                            </a>
                                        </li>
                                        <li>
                                            <a class="dropdown-item" href="#">
                                                <i class="bi bi-cash-stack text-color-yellow me-2"></i>
                                                Raising platform's
                                            </a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="nav-item pe-3">
                                    <a href="#" class="nav-link  link-dark">
                                        What we do
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </nav>
                </div>

                <!-- User's menu -->
                <div class="col-3 align-self-center">
                    <div class="d-none d-lg-block text-end">
                        {% if user.is_authenticated %}
                            <div class="dropdown">
                                <button type="button" class="btn" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <img class="rounded-circle header-profile-user" src="{% static 'images/users/user.jpg' %}" alt="">
                                    <span class="text-color-blue"> {{ user.username }} </span>
                                    <i class="bi bi-chevron-down text-color-blue"></i>
                                </button>
                                <div class="dropdown-menu dropdown-menu-end">
                                    <a class="dropdown-item" href="#">
                                        <i class="bi bi-star text-color-yellow d-inline-block"></i>
                                        <span class="align-middle ps-2">Watchlist</span>
                                    </a>
                                    <a class="dropdown-item" href="#">
                                        <i class="bi bi-briefcase text-color-yellow d-inline-block"></i>
                                        <span class="align-middle ps-2">Portfolio</span>
                                    </a>
                                    <a class="dropdown-item" href="#">
                                        <i class="bi bi-arrow-repeat  text-color-yellow d-inline-block"></i>
                                        <span class="align-middle ps-2">Change password</span>
                                    </a>

                                    <div class="dropdown-divider"></div>
                                    <form class="dropdown-item" action="{% url 'logoutuser' %}" method="POST">
                                        {% csrf_token %}
                                        <i class="bi bi-door-open text-color-yellow d-inline-block"></i>
                                        <button type="submit" class="align-middle btn text-danger">Logout</button>
                                    </form>
                                </div>
                            </div>

                        {% else %}
                            <div>
                                <div class="d-inline-block">
                                    <a href="{% url 'loginuser' %}">
                                        <button type="button" class="btn btn-login pe-3 ps-3 me-3" style="text-decoration: none">
                                            Log In
                                        </button>
                                    </a>
                                </div>
                                <div class="d-inline-block">
                                    <a href="{% url 'signupuser' %}">
                                        <button type="button" class="btn btn-primary pe-3 ps-3" style="text-decoration: none">Sign up</button>
                                    </a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
		</div>
	</div>
{% endblock header %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
         Это первая страница
    </div>

{% endblock %}

templates/topstatwidget.html
{% load static %}
{% block topstatwiget %}

	<div class="topstatwidget d-none d-lg-block">
		<div class="container my-1">
			<div class="d-flex justify-content-between">
				<!-- Statistic's widget -->
				<ul class="nav align-content-center">
					<li class="me-4">Projects: <span class="text-color-blue">{{  equity_projects.count  }}124054545</span></li>
					<li class="me-4">Brokers: <span class="text-color-blue">{{  equity_projects.count  }}415</span></li>
					<li class="me-4">Users: <span class="text-color-blue">{{  equity_projects.count  }}2155263</span></li>
					<li class="me-4">Invested: <span class="text-color-blue"><span class="bi bi-currency-euro"></span>{{  equity_projects.count  }}150654548</span></li>
					<!-- Search Bar -->
					<li>
						<form>
							<input type="search" class="searchbar-form" placeholder="Search..." aria-label="Search">
						</form>
					</li>
				</ul>
				<!-- Language choice -->
				<div class="dropdown">
					<button type="button" class="btn btn-lang" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<span> English </span>
						<i class="bi bi-chevron-down"></i>
					</button>
					<div class="dropdown-menu dropdown-menu-end text-center">
						<a class="dropdown-item" data-lang="en"> <span class="align-middle text-color-dark-grey">English</span> </a>
						<a class="dropdown-item" data-lang="es"> <span class="align-middle text-color-dark-grey">Espa&#328;ol</span> </a>
						<a class="dropdown-item" data-lang="de"> <span class="align-middle text-color-dark-grey">Deutsche</span> </a>
						<a class="dropdown-item" data-lang="it"> <span class="align-middle text-color-dark-grey">Italiano</span> </a>
                        <a class="dropdown-item" data-lang="fr"> <span class="align-middle text-color-dark-grey">Fran&#231;ais</span> </a>
                        <a class="dropdown-item" data-lang="po"> <span class="align-middle text-color-dark-grey">Portugu&#519;s</span> </a>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock topstatwiget %}